-- ---------------------------------------------------------------------------
-- V2__seed.sql — demo data.
--
-- The point of this file is that `make up-node` on a clean machine opens onto a
-- shop someone would believe. No "Product 1". Real Thai product names, prices
-- that make sense in satang, a category tree with actual depth.
--
-- Three cases are planted deliberately, because each one is a demo or a test
-- that cannot be performed without it:
--
--   * TOTE-M has stock_on_hand = 1 — the concurrency demo. Fire 20 concurrent
--     checkouts at it; exactly one may win.
--   * kitchen-knife-set has every variant at 0 — the sold-out UI state, which
--     is otherwise the kind of thing nobody notices is unstyled until a demo.
--   * cast-iron-pot, cotton-sheet-set-400tc and canvas-tote-bag each have
--     variants at different prices, so sort=price_asc has something to sort and
--     min_price_cents has something to be wrong about.
--
-- Two products are not active on purpose: one draft, one archived. Without them
-- "the catalogue shows only active products" is an untested claim.
--
-- IDs are fixed rather than generated so that tests and fixtures can refer to
-- them. They are UUIDv7-shaped for consistency with what the applications
-- generate at runtime, though nothing depends on their timestamps.
--
-- Images point at picsum.photos, seeded per slug so each product keeps the same
-- picture across re-seeds. Deliberate: a fabricated Unsplash photo ID that
-- 404s looks far worse than a generic photo that always loads. Swapping in
-- curated product shots belongs to task 6.2.
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- Users
--
-- All three share the password `DemoPass123!`. These are argon2id PHC strings
-- generated by migrations/.gen-seed-hashes.mjs with the OWASP parameters the
-- auth module must also use (m=19456, t=2, p=1) — if task 2.2 picks different
-- parameters, these users stop being able to log in.
--
-- Demo credentials in a demo seed. Nothing here is a secret, and nothing here
-- should ever be reachable from a real deployment.
-- ===========================================================================

INSERT INTO users (id, email, password_hash, full_name, role) VALUES
    ('01930000-0000-7000-8000-000000000001',
     'admin@vibecode.shop',
     '$argon2id$v=19$m=19456,t=2,p=1$zK9T22x92XVMPC1MPKqTHg$FUwxVAPvbEr+pW9RPTZ0/8quAXIv6seUGEK2vPtEpLI',
     'ผู้ดูแลระบบ', 'admin'),
    ('01930000-0000-7000-8000-000000000002',
     'somchai@example.com',
     '$argon2id$v=19$m=19456,t=2,p=1$dYW1SOVM5rLsbvC6pDzOgw$kKaz9I/pIJ/puKmLjdeMR3XPmwpOevP5Ak4Bq6hHcdo',
     'สมชาย ใจดี', 'customer'),
    ('01930000-0000-7000-8000-000000000003',
     'pimchanok@example.com',
     '$argon2id$v=19$m=19456,t=2,p=1$wY3WmZLkT60gHLfekNMaZg$arIfrHXGDKxZbJhk5pykNpB4NMgPX2rclqGj9BeKTUo',
     'พิมพ์ชนก วงศ์สุวรรณ', 'customer');

-- ===========================================================================
-- Categories
--
-- Three roots with real depth beneath two of them. The nesting is not
-- decoration: `categorySlug=clothing` must return the hoodie filed directly
-- under it *and* everything under t-shirts, shirts and trousers. A flat seed
-- would leave the recursive CTE in both backends completely unexercised.
-- ===========================================================================

INSERT INTO categories (id, parent_id, slug, name, position) VALUES
    ('01930001-0000-7000-8000-000000000001', NULL,
     'clothing',    'เสื้อผ้า',           1),
    ('01930001-0000-7000-8000-000000000002', '01930001-0000-7000-8000-000000000001',
     't-shirts',    'เสื้อยืด',            1),
    ('01930001-0000-7000-8000-000000000003', '01930001-0000-7000-8000-000000000001',
     'shirts',      'เสื้อเชิ้ต',          2),
    ('01930001-0000-7000-8000-000000000004', '01930001-0000-7000-8000-000000000001',
     'trousers',    'กางเกง',             3),
    ('01930001-0000-7000-8000-000000000005', NULL,
     'home-living', 'ของใช้ในบ้าน',       2),
    ('01930001-0000-7000-8000-000000000006', '01930001-0000-7000-8000-000000000005',
     'kitchen',     'เครื่องครัว',         1),
    ('01930001-0000-7000-8000-000000000007', '01930001-0000-7000-8000-000000000005',
     'bedding',     'เครื่องนอน',          2),
    ('01930001-0000-7000-8000-000000000008', NULL,
     'bags',        'กระเป๋า',             3);

-- ===========================================================================
-- Products
--
-- min_price_cents is left at its default here and computed at the end of this
-- file, once the variants exist. Both backends have to maintain it from then on.
-- ===========================================================================

INSERT INTO products (id, category_id, slug, name, description, status) VALUES
    -- t-shirts
    ('01930002-0000-7000-8000-000000000001', '01930001-0000-7000-8000-000000000002',
     'crewneck-organic-tee', 'เสื้อยืดคอกลม ผ้าฝ้ายออร์แกนิก',
     'เสื้อยืดคอกลมผ้าฝ้ายออร์แกนิก 100% ทอแน่น น้ำหนัก 220 แกรม ทรงตรงไม่ยืดย้วยหลังซัก เย็บตะเข็บคู่ที่ไหล่และชายเสื้อ ใส่ได้ทุกวันทั้งตัวเดียวและใส่ซ้อน',
     'active'),
    ('01930002-0000-7000-8000-000000000002', '01930001-0000-7000-8000-000000000002',
     'oversized-boxy-tee', 'เสื้อยืดโอเวอร์ไซส์ทรงกล่อง',
     'ทรงกล่องไหล่ตก ตัวกว้างแต่ไม่เทอะทะ ผ้าฝ้ายหนา 240 แกรม ทิ้งตัวสวยไม่ต้องรีด เหมาะกับคนที่ชอบใส่หลวมแต่ยังต้องการทรงที่ชัดเจน',
     'active'),
    -- Draft on purpose: must never appear in the catalogue.
    ('01930002-0000-7000-8000-000000000003', '01930001-0000-7000-8000-000000000002',
     'long-sleeve-tee', 'เสื้อยืดแขนยาวคอกลม',
     'เสื้อยืดแขนยาวผ้าฝ้ายผสมโมดัล นุ่มลื่นกว่าฝ้ายล้วน ปลายแขนจั๊มพอดีข้อมือ ยังอยู่ระหว่างเตรียมภาพสินค้า',
     'draft'),
    -- shirts
    ('01930002-0000-7000-8000-000000000004', '01930001-0000-7000-8000-000000000003',
     'oxford-button-down-shirt', 'เสื้อเชิ้ตออกซ์ฟอร์ดคอปกกระดุม',
     'ผ้าออกซ์ฟอร์ดทอแน่นจากฝ้ายยาวพิเศษ คอปกมีกระดุมยึด ทรงกึ่งพอดีตัวใส่ได้ทั้งในกางเกงและปล่อยชาย ยิ่งซักยิ่งนุ่มขึ้น',
     'active'),
    ('01930002-0000-7000-8000-000000000005', '01930001-0000-7000-8000-000000000003',
     'linen-camp-shirt', 'เสื้อเชิ้ตลินินคอปกเปิด',
     'ลินินฝรั่งเศส 100% ระบายอากาศดีมากสำหรับอากาศร้อน คอปกเปิดทรงคิวบา ใส่สบายแบบไม่ต้องรีดให้เรียบกริบ ยับตามธรรมชาติของผ้า',
     'active'),
    -- trousers
    ('01930002-0000-7000-8000-000000000006', '01930001-0000-7000-8000-000000000004',
     'chino-trousers', 'กางเกงชิโน่ขายาว',
     'ผ้าทวิลฝ้ายยืดเล็กน้อย ทรงขาเรียวแต่ไม่รัด กระเป๋าหลังแบบมีฝา เอวมีซับในกันระคาย ใส่ทำงานได้และใส่เที่ยวได้',
     'active'),
    ('01930002-0000-7000-8000-000000000007', '01930001-0000-7000-8000-000000000004',
     'cotton-shorts', 'กางเกงขาสั้นผ้าฝ้าย',
     'ขาสั้นเหนือเข่า ผ้าฝ้ายทอเนื้อแน่นแต่บาง เอวยางยืดพร้อมเชือกรูด มีกระเป๋าข้างลึกพอใส่มือถือได้จริง',
     'active'),
    -- Archived on purpose: order history referencing it must survive.
    ('01930002-0000-7000-8000-000000000008', '01930001-0000-7000-8000-000000000004',
     'fleece-sweatpants', 'กางเกงวอร์มผ้าสำลี',
     'ผ้าสำลีขูดขนด้านใน อบอุ่นแต่ไม่หนัก ปลายขาจั๊ม เลิกผลิตรุ่นนี้แล้ว',
     'archived'),
    -- Filed directly on a root category, to prove subtree filtering includes both.
    ('01930002-0000-7000-8000-000000000009', '01930001-0000-7000-8000-000000000001',
     'zip-up-hoodie', 'เสื้อฮู้ดซิปหน้า',
     'ผ้าสำลีหนา 320 แกรม ซิปโลหะเดินเรียบ ฮู้ดสองชั้นอยู่ทรงไม่แบน กระเป๋าหน้าเย็บติดแน่น เป็นตัวที่หยิบใส่ทับได้ทุกชุด',
     'active'),
    -- kitchen
    ('01930002-0000-7000-8000-00000000000a', '01930001-0000-7000-8000-000000000006',
     'matte-ceramic-mug', 'แก้วเซรามิกเคลือบด้าน',
     'เซรามิกเผาอุณหภูมิสูง เคลือบด้านทั้งใบ จับไม่ลื่นมือ ความจุ 350 มล. เข้าไมโครเวฟและเครื่องล้างจานได้',
     'active'),
    ('01930002-0000-7000-8000-00000000000b', '01930001-0000-7000-8000-000000000006',
     'cast-iron-pot', 'หม้อเหล็กหล่อเคลือบอีนาเมล',
     'เหล็กหล่อทั้งใบเคลือบอีนาเมล เก็บความร้อนได้นานและกระจายความร้อนสม่ำเสมอ ฝาหนักช่วยกักไอน้ำ ใช้ได้กับเตาทุกประเภทรวมเตาแม่เหล็กไฟฟ้า',
     'active'),
    -- Every variant sold out: the state most portfolios forget to style.
    ('01930002-0000-7000-8000-00000000000c', '01930001-0000-7000-8000-000000000006',
     'kitchen-knife-set', 'ชุดมีดทำครัวสเตนเลส 3 ชิ้น',
     'มีดเชฟ มีดปอก และมีดขนมปัง เหล็กสเตนเลสชุบแข็ง ด้ามจับทรงโค้งเข้ามือ มาพร้อมแท่นไม้ยางพารา สินค้าหมดชั่วคราว',
     'active'),
    -- bedding
    ('01930002-0000-7000-8000-00000000000d', '01930001-0000-7000-8000-000000000007',
     'cotton-sheet-set-400tc', 'ชุดผ้าปูที่นอนคอตตอน 400 เส้น',
     'คอตตอน 100% ทอ 400 เส้นต่อตารางนิ้ว สัมผัสเย็นและเรียบ ชุดประกอบด้วยผ้าปูรัดมุม ปลอกหมอน 2 ใบ และผ้านวมคลุม',
     'active'),
    ('01930002-0000-7000-8000-00000000000e', '01930001-0000-7000-8000-000000000007',
     'down-alt-pillow', 'หมอนหนุนใยสังเคราะห์เกรดพรีเมียม',
     'ใยสังเคราะห์เลียนแบบขนเป็ด คืนตัวดีไม่ยุบเป็นก้อน ปลอกนอกคอตตอนทอแน่นกันไรฝุ่น ซักเครื่องได้',
     'active'),
    -- bags
    ('01930002-0000-7000-8000-00000000000f', '01930001-0000-7000-8000-000000000008',
     'canvas-tote-bag', 'กระเป๋าผ้าแคนวาสสะพายไหล่',
     'แคนวาสฝ้ายหนา 16 ออนซ์ ทรงตั้งได้เอง สายสะพายเย็บย้ำห้าจุด มีกระเป๋าซิปด้านใน ใส่โน้ตบุ๊ก 14 นิ้วได้พอดี',
     'active');

-- ===========================================================================
-- Variants
--
-- Prices are in satang: 39000 = ฿390.00. Stock figures vary per size the way a
-- real shop's would — the popular middle sizes deeper than the ends.
-- ===========================================================================

INSERT INTO product_variants (product_id, sku, name, price_cents, stock_on_hand, position) VALUES
    -- crewneck tee, one price across sizes
    ('01930002-0000-7000-8000-000000000001', 'TEE-CR-S',  'ขาว / S',   39000, 25, 1),
    ('01930002-0000-7000-8000-000000000001', 'TEE-CR-M',  'ขาว / M',   39000, 40, 2),
    ('01930002-0000-7000-8000-000000000001', 'TEE-CR-L',  'ขาว / L',   39000, 35, 3),
    ('01930002-0000-7000-8000-000000000001', 'TEE-CR-XL', 'ขาว / XL',  39000, 12, 4),
    -- oversized tee
    ('01930002-0000-7000-8000-000000000002', 'TEE-OV-M',  'ดำ / M',    45000, 18, 1),
    ('01930002-0000-7000-8000-000000000002', 'TEE-OV-L',  'ดำ / L',    45000, 22, 2),
    ('01930002-0000-7000-8000-000000000002', 'TEE-OV-XL', 'ดำ / XL',   45000,  9, 3),
    -- long sleeve tee (draft product)
    ('01930002-0000-7000-8000-000000000003', 'TEE-LS-M',  'กรม / M',   52000,  0, 1),
    ('01930002-0000-7000-8000-000000000003', 'TEE-LS-L',  'กรม / L',   52000,  0, 2),
    ('01930002-0000-7000-8000-000000000003', 'TEE-LS-XL', 'กรม / XL',  52000,  0, 3),
    -- oxford shirt
    ('01930002-0000-7000-8000-000000000004', 'SHT-OX-S',  'ฟ้า / S',   89000, 14, 1),
    ('01930002-0000-7000-8000-000000000004', 'SHT-OX-M',  'ฟ้า / M',   89000, 20, 2),
    ('01930002-0000-7000-8000-000000000004', 'SHT-OX-L',  'ฟ้า / L',   89000, 16, 3),
    ('01930002-0000-7000-8000-000000000004', 'SHT-OX-XL', 'ฟ้า / XL',  89000,  6, 4),
    -- linen shirt
    ('01930002-0000-7000-8000-000000000005', 'SHT-LN-S',  'ครีม / S',  119000,  8, 1),
    ('01930002-0000-7000-8000-000000000005', 'SHT-LN-M',  'ครีม / M',  119000, 11, 2),
    ('01930002-0000-7000-8000-000000000005', 'SHT-LN-L',  'ครีม / L',  119000,  5, 3),
    -- chinos, by waist
    ('01930002-0000-7000-8000-000000000006', 'TRS-CH-30', 'เบจ / 30',  129000, 10, 1),
    ('01930002-0000-7000-8000-000000000006', 'TRS-CH-32', 'เบจ / 32',  129000, 15, 2),
    ('01930002-0000-7000-8000-000000000006', 'TRS-CH-34', 'เบจ / 34',  129000, 12, 3),
    ('01930002-0000-7000-8000-000000000006', 'TRS-CH-36', 'เบจ / 36',  129000,  7, 4),
    -- shorts
    ('01930002-0000-7000-8000-000000000007', 'TRS-SH-S',  'เขียว / S', 79000, 20, 1),
    ('01930002-0000-7000-8000-000000000007', 'TRS-SH-M',  'เขียว / M', 79000, 24, 2),
    ('01930002-0000-7000-8000-000000000007', 'TRS-SH-L',  'เขียว / L', 79000, 13, 3),
    -- sweatpants (archived product)
    ('01930002-0000-7000-8000-000000000008', 'TRS-SW-M',  'เทา / M',   99000,  4, 1),
    ('01930002-0000-7000-8000-000000000008', 'TRS-SW-L',  'เทา / L',   99000,  6, 2),
    ('01930002-0000-7000-8000-000000000008', 'TRS-SW-XL', 'เทา / XL',  99000,  3, 3),
    -- hoodie
    ('01930002-0000-7000-8000-000000000009', 'HOD-ZP-M',  'ดำ / M',   159000, 11, 1),
    ('01930002-0000-7000-8000-000000000009', 'HOD-ZP-L',  'ดำ / L',   159000, 14, 2),
    ('01930002-0000-7000-8000-000000000009', 'HOD-ZP-XL', 'ดำ / XL',  159000,  8, 3),
    -- mug, by colour
    ('01930002-0000-7000-8000-00000000000a', 'MUG-CR-WH', 'ขาวนวล',    29000, 30, 1),
    ('01930002-0000-7000-8000-00000000000a', 'MUG-CR-GY', 'เทาหิน',    29000, 28, 2),
    ('01930002-0000-7000-8000-00000000000a', 'MUG-CR-TR', 'เขียวดินเผา', 29000, 22, 3),
    -- cast iron pot: prices differ by size, so price_asc has real work to do
    ('01930002-0000-7000-8000-00000000000b', 'POT-CI-24', '24 ซม. / 3.5 ลิตร', 249000, 6, 1),
    ('01930002-0000-7000-8000-00000000000b', 'POT-CI-28', '28 ซม. / 5.5 ลิตร', 329000, 4, 2),
    -- knife set: sold out, on purpose
    ('01930002-0000-7000-8000-00000000000c', 'KNF-ST-3P', 'ชุด 3 ชิ้น', 189000,  0, 1),
    -- sheet set: three sizes, three prices
    ('01930002-0000-7000-8000-00000000000d', 'BED-SS-35', '3.5 ฟุต',  129000, 12, 1),
    ('01930002-0000-7000-8000-00000000000d', 'BED-SS-50', '5 ฟุต',    149000, 10, 2),
    ('01930002-0000-7000-8000-00000000000d', 'BED-SS-60', '6 ฟุต',    179000,  7, 3),
    -- pillow
    ('01930002-0000-7000-8000-00000000000e', 'PLW-DA-SF', 'นุ่ม',      69000, 25, 1),
    ('01930002-0000-7000-8000-00000000000e', 'PLW-DA-FM', 'แน่น',      69000, 18, 2),
    -- tote: three sizes, three prices, and the single unit the concurrency
    -- demo fires at. Keep TOTE-M at exactly 1.
    ('01930002-0000-7000-8000-00000000000f', 'TOTE-S',    'เล็ก',      59000, 16, 1),
    ('01930002-0000-7000-8000-00000000000f', 'TOTE-M',    'กลาง',      69000,  1, 2),
    ('01930002-0000-7000-8000-00000000000f', 'TOTE-L',    'ใหญ่',      89000,  9, 3);

-- ===========================================================================
-- Images
--
-- Seeded by slug so a product keeps its picture across `make clean`.
-- ===========================================================================

INSERT INTO product_images (product_id, url, alt, position)
SELECT p.id,
       'https://picsum.photos/seed/' || p.slug || '/800/800',
       p.name,
       0
FROM products p;

-- A second angle for the products most likely to be opened in a demo.
INSERT INTO product_images (product_id, url, alt, position)
SELECT p.id,
       'https://picsum.photos/seed/' || p.slug || '-alt/800/800',
       p.name || ' (มุมที่สอง)',
       1
FROM products p
WHERE p.slug IN ('crewneck-organic-tee', 'oxford-button-down-shirt',
                 'cast-iron-pot', 'canvas-tote-bag');

-- ===========================================================================
-- Derived columns
--
-- The only MIN() over variants anyone should ever write: once, at seed time.
-- At runtime this column is maintained on write, because sort=price_asc reads
-- it on every catalogue request and a subquery there cannot use an index.
-- ===========================================================================

UPDATE products p
SET min_price_cents = COALESCE((
        SELECT MIN(v.price_cents)
        FROM product_variants v
        WHERE v.product_id = p.id AND v.is_active
    ), 0);

-- ===========================================================================
-- Self-check
--
-- A seed that half-applied is worse than one that failed, because the shop
-- still looks fine while the demo cases have quietly gone. These assertions run
-- inside the same migration, so a botched edit fails `make up-node` loudly
-- instead of surfacing three phases later as a flaky concurrency test.
-- ===========================================================================

DO $$
DECLARE
    v_count integer;
BEGIN
    SELECT count(*) INTO v_count FROM users;
    IF v_count <> 3 THEN
        RAISE EXCEPTION 'expected 3 users, found %', v_count;
    END IF;

    SELECT count(*) INTO v_count FROM categories;
    IF v_count <> 8 THEN
        RAISE EXCEPTION 'expected 8 categories, found %', v_count;
    END IF;

    SELECT count(*) INTO v_count FROM products;
    IF v_count <> 15 THEN
        RAISE EXCEPTION 'expected 15 products, found %', v_count;
    END IF;

    SELECT count(*) INTO v_count FROM product_variants;
    IF v_count <> 44 THEN
        RAISE EXCEPTION 'expected 44 variants, found %', v_count;
    END IF;

    -- The concurrency demo needs exactly one unit, not two and not none.
    SELECT stock_on_hand INTO v_count
    FROM product_variants WHERE sku = 'TOTE-M';
    IF v_count <> 1 THEN
        RAISE EXCEPTION 'TOTE-M must hold exactly 1 unit for the concurrency demo, found %', v_count;
    END IF;

    -- The sold-out product must actually be sold out.
    SELECT sum(v.stock_on_hand) INTO v_count
    FROM product_variants v
    JOIN products p ON p.id = v.product_id
    WHERE p.slug = 'kitchen-knife-set';
    IF v_count <> 0 THEN
        RAISE EXCEPTION 'kitchen-knife-set must be fully out of stock, found % units', v_count;
    END IF;

    -- price_asc needs products whose variants disagree on price.
    SELECT count(*) INTO v_count FROM (
        SELECT product_id FROM product_variants
        GROUP BY product_id HAVING count(DISTINCT price_cents) > 1
    ) multi;
    IF v_count < 3 THEN
        RAISE EXCEPTION 'expected at least 3 multi-price products for price_asc, found %', v_count;
    END IF;

    -- The catalogue must have something to hide.
    SELECT count(*) INTO v_count FROM products WHERE status <> 'active';
    IF v_count < 2 THEN
        RAISE EXCEPTION 'expected a draft and an archived product, found % non-active', v_count;
    END IF;

    -- The denormalised column has to agree with the variants it summarises.
    SELECT count(*) INTO v_count
    FROM products p
    WHERE p.min_price_cents <> COALESCE((
        SELECT MIN(v.price_cents) FROM product_variants v
        WHERE v.product_id = p.id AND v.is_active
    ), 0);
    IF v_count <> 0 THEN
        RAISE EXCEPTION 'min_price_cents disagrees with variants on % products', v_count;
    END IF;

    RAISE NOTICE 'seed verified: 3 users, 8 categories, 15 products, 44 variants';
END
$$;
